/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/28391Vp8Yra
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Dialog, DialogContent } from "@/components/ui/dialog"

export function ABHACARD() {
  return (
    <Dialog defaultOpen>
      <DialogContent className="bg-[#f0f0f0] bg-opacity-80 backdrop-blur-sm p-12 rounded-2xl w-full max-w-[600px] mx-auto animate-fade-in-up">
        <div className="flex flex-col items-center gap-8">
          <div className="bg-[#4CAF50] rounded-t-2xl w-full py-12 flex justify-center">
            <img
              src="/placeholder.svg"
              alt="Medical Card"
              width={200}
              height={200}
              className="object-contain"
              style={{ aspectRatio: "200/200", objectFit: "cover" }}
            />
          </div>
          <div className="grid gap-4 text-center">
            <h3 className="text-3xl font-bold">John Doe</h3>
            <p className="text-xl font-medium">Medical Card Number: 1234 5678 9012</p>
            <p className="text-muted-foreground text-lg">
              Date of Birth: 01/01/1990
              <br />
              Gender: Male
              <br />
              Address: 123 Main St, Anytown USA
            </p>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
