/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/rJyGwsDkt4T
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function PopUp doctor() {
  return (
    <Card className="w-full max-w-md p-6 grid gap-6">
      <div className="flex items-center gap-4">
        <Avatar>
          <AvatarImage src="/placeholder-user.jpg" alt="Doctor Avatar" />
          <AvatarFallback>DR</AvatarFallback>
        </Avatar>
        <div className="grid gap-1 flex-1">
          <h3 className="text-xl font-semibold">Dr. Sarah Johnson</h3>
          <div className="text-muted-foreground">
            <span className="font-medium">Department:</span> Cardiology
          </div>
          <div className="text-muted-foreground">
            <span className="font-medium">Role:</span> Cardiologist
          </div>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">Allocate</Button>
          <Button>Cancel</Button>
        </div>
      </div>
    </Card>
  )
}
